/*

IF ANY ASYNC OPERATIONS ARE BEING PERFORMED ON THE RESPECTIVE SCREEN THEN THOSE METHODS WILL BE WRITTEN HERE IN THIS REPOSITIRY FOLDE AND THET WILL CALL THE RESPECTIVE FOLDEER FROM THE DATA FOLDER.

FOR EXMAPOLE:

Login_repo Logic

Signup repos login

forgot password repo logic
*/
